"""Add video model for Phase 5

Revision ID: 6171e595e298
Revises: 74130f556607
Create Date: 2025-12-14 19:32:16.557310

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6171e595e298"
down_revision: str | None = "74130f556607"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos",
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("script_id", sa.Uuid(), nullable=False),
        sa.Column("video_path", sa.String(length=500), nullable=False),
        sa.Column("thumbnail_path", sa.String(length=500), nullable=False),
        sa.Column("audio_path", sa.String(length=500), nullable=True),
        sa.Column("subtitle_path", sa.String(length=500), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("resolution", sa.String(length=20), nullable=False),
        sa.Column("fps", sa.Integer(), nullable=False),
        sa.Column("tts_service", sa.String(length=50), nullable=False),
        sa.Column("tts_voice_id", sa.String(length=100), nullable=False),
        sa.Column("visual_sources", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("generation_time_seconds", sa.Integer(), nullable=True),
        sa.Column("generation_metadata", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
            name=op.f("fk_videos_channel_id_channels"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["script_id"],
            ["scripts.id"],
            name=op.f("fk_videos_script_id_scripts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_videos")),
    )
    op.create_index("idx_video_channel_status", "videos", ["channel_id", "status"], unique=False)
    op.create_index("idx_video_script", "videos", ["script_id"], unique=False)
    op.create_index(op.f("ix_videos_channel_id"), "videos", ["channel_id"], unique=False)
    op.create_index(op.f("ix_videos_id"), "videos", ["id"], unique=False)
    op.create_index(op.f("ix_videos_script_id"), "videos", ["script_id"], unique=False)
    op.create_index(op.f("ix_videos_status"), "videos", ["status"], unique=False)
    op.create_index(op.f("ix_content_chunks_id"), "content_chunks", ["id"], unique=False)
    op.create_index(op.f("ix_scripts_id"), "scripts", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scripts_id"), table_name="scripts")
    op.drop_index(op.f("ix_content_chunks_id"), table_name="content_chunks")
    op.drop_index(op.f("ix_videos_status"), table_name="videos")
    op.drop_index(op.f("ix_videos_script_id"), table_name="videos")
    op.drop_index(op.f("ix_videos_id"), table_name="videos")
    op.drop_index(op.f("ix_videos_channel_id"), table_name="videos")
    op.drop_index("idx_video_script", table_name="videos")
    op.drop_index("idx_video_channel_status", table_name="videos")
    op.drop_table("videos")
    # ### end Alembic commands ###
