"""Add Channel, Persona, Source, and Topic models

Revision ID: c264d90645b4
Revises:
Create Date: 2025-12-11 11:25:10.655625

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c264d90645b4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("youtube_channel_id", sa.String(length=50), nullable=True),
        sa.Column("youtube_handle", sa.String(length=50), nullable=True),
        sa.Column(
            "status", sa.Enum("ACTIVE", "PAUSED", "ARCHIVED", name="channelstatus"), nullable=False
        ),
        sa.Column("topic_config", sa.JSON(), nullable=False),
        sa.Column("source_config", sa.JSON(), nullable=False),
        sa.Column("content_config", sa.JSON(), nullable=False),
        sa.Column("operation_config", sa.JSON(), nullable=False),
        sa.Column("default_hashtags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("default_links", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channels")),
    )
    op.create_index(op.f("ix_channels_id"), "channels", ["id"], unique=False)
    op.create_index(op.f("ix_channels_status"), "channels", ["status"], unique=False)
    op.create_index(
        op.f("ix_channels_youtube_channel_id"), "channels", ["youtube_channel_id"], unique=True
    )
    op.create_table(
        "sources",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "API", "RSS", "SCRAPER", "BROWSER", "VIDEO", "SOCIAL", "TREND", name="sourcetype"
            ),
            nullable=False,
        ),
        sa.Column(
            "region", sa.Enum("DOMESTIC", "FOREIGN", "GLOBAL", name="sourceregion"), nullable=False
        ),
        sa.Column("connection_config", sa.JSON(), nullable=False),
        sa.Column("parser_config", sa.JSON(), nullable=False),
        sa.Column("default_filters", sa.JSON(), nullable=False),
        sa.Column("cron_expression", sa.String(length=50), nullable=True),
        sa.Column("rate_limit", sa.Integer(), nullable=False),
        sa.Column("credibility", sa.Float(), nullable=False),
        sa.Column("categories", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_index(op.f("ix_sources_id"), "sources", ["id"], unique=False)
    op.create_index(op.f("ix_sources_name"), "sources", ["name"], unique=True)
    op.create_index(op.f("ix_sources_type"), "sources", ["type"], unique=False)
    op.create_table(
        "channel_sources",
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("custom_config", sa.JSON(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
            name=op.f("fk_channel_sources_channel_id_channels"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_channel_sources_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("channel_id", "source_id", name=op.f("pk_channel_sources")),
    )
    op.create_table(
        "personas",
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("tagline", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("expertise", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("voice_gender", sa.String(length=10), nullable=True),
        sa.Column(
            "tts_service",
            sa.Enum("EDGE_TTS", "ELEVENLABS", "CLOVA", name="ttsservice"),
            nullable=False,
        ),
        sa.Column("voice_id", sa.String(length=100), nullable=True),
        sa.Column("voice_settings", sa.JSON(), nullable=True),
        sa.Column("communication_style", sa.JSON(), nullable=True),
        sa.Column("perspective", sa.JSON(), nullable=True),
        sa.Column("examples", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
            name=op.f("fk_personas_channel_id_channels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personas")),
        sa.UniqueConstraint("channel_id", name=op.f("uq_personas_channel_id")),
    )
    op.create_index(op.f("ix_personas_id"), "personas", ["id"], unique=False)
    op.create_table(
        "topics",
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("title_original", sa.Text(), nullable=False),
        sa.Column("title_translated", sa.Text(), nullable=True),
        sa.Column("title_normalized", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("categories", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("keywords", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("entities", sa.JSON(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("score_source", sa.Float(), nullable=False),
        sa.Column("score_freshness", sa.Float(), nullable=False),
        sa.Column("score_trend", sa.Float(), nullable=False),
        sa.Column("score_relevance", sa.Float(), nullable=False),
        sa.Column("score_total", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", "USED", "EXPIRED", name="topicstatus"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
            name=op.f("fk_topics_channel_id_channels"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_topics_source_id_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
    )
    op.create_index("idx_topic_channel_status", "topics", ["channel_id", "status"], unique=False)
    op.create_index("idx_topic_score", "topics", ["channel_id", "score_total"], unique=False)
    op.create_index(op.f("ix_topics_channel_id"), "topics", ["channel_id"], unique=False)
    op.create_index(op.f("ix_topics_content_hash"), "topics", ["content_hash"], unique=False)
    op.create_index(op.f("ix_topics_expires_at"), "topics", ["expires_at"], unique=False)
    op.create_index(op.f("ix_topics_id"), "topics", ["id"], unique=False)
    op.create_index(op.f("ix_topics_score_total"), "topics", ["score_total"], unique=False)
    op.create_index(op.f("ix_topics_status"), "topics", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topics_status"), table_name="topics")
    op.drop_index(op.f("ix_topics_score_total"), table_name="topics")
    op.drop_index(op.f("ix_topics_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_expires_at"), table_name="topics")
    op.drop_index(op.f("ix_topics_content_hash"), table_name="topics")
    op.drop_index(op.f("ix_topics_channel_id"), table_name="topics")
    op.drop_index("idx_topic_score", table_name="topics")
    op.drop_index("idx_topic_channel_status", table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_personas_id"), table_name="personas")
    op.drop_table("personas")
    op.drop_table("channel_sources")
    op.drop_index(op.f("ix_sources_type"), table_name="sources")
    op.drop_index(op.f("ix_sources_name"), table_name="sources")
    op.drop_index(op.f("ix_sources_id"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_channels_youtube_channel_id"), table_name="channels")
    op.drop_index(op.f("ix_channels_status"), table_name="channels")
    op.drop_index(op.f("ix_channels_id"), table_name="channels")
    op.drop_table("channels")
    # ### end Alembic commands ###
