"""add_upload_performance_series_tables

Revision ID: b46978c57b8c
Revises: replace_title_text_with_headline
Create Date: 2026-02-05 01:26:18.236750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b46978c57b8c"
down_revision: Union[str, None] = "replace_title_text_with_headline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "series",
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("criteria_keywords", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("criteria_categories", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("min_similarity", sa.Float(), nullable=False),
        sa.Column("episode_count", sa.Integer(), nullable=False),
        sa.Column("avg_views", sa.Float(), nullable=False),
        sa.Column("avg_engagement", sa.Float(), nullable=False),
        sa.Column("trend", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("auto_detected", sa.Boolean(), nullable=False),
        sa.Column("confirmed_by_user", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
            name=op.f("fk_series_channel_id_channels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_series")),
    )
    op.create_index("idx_series_channel", "series", ["channel_id"], unique=False)
    op.create_index("idx_series_channel_status", "series", ["channel_id", "status"], unique=False)
    op.create_index("idx_series_status", "series", ["status"], unique=False)
    op.create_index(op.f("ix_series_channel_id"), "series", ["channel_id"], unique=False)
    op.create_index(op.f("ix_series_id"), "series", ["id"], unique=False)
    op.create_table(
        "uploads",
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column("youtube_video_id", sa.String(length=50), nullable=True),
        sa.Column("youtube_url", sa.String(length=200), nullable=True),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("category_id", sa.String(length=10), nullable=False),
        sa.Column("privacy_status", sa.String(length=20), nullable=False),
        sa.Column("is_shorts", sa.Boolean(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("upload_status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_uploads_video_id_videos"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploads")),
    )
    op.create_index("idx_upload_scheduled", "uploads", ["scheduled_at"], unique=False)
    op.create_index("idx_upload_status", "uploads", ["upload_status"], unique=False)
    op.create_index("idx_upload_youtube_id", "uploads", ["youtube_video_id"], unique=False)
    op.create_index(op.f("ix_uploads_id"), "uploads", ["id"], unique=False)
    op.create_index(op.f("ix_uploads_video_id"), "uploads", ["video_id"], unique=True)
    op.create_index(
        op.f("ix_uploads_youtube_video_id"), "uploads", ["youtube_video_id"], unique=True
    )
    op.create_table(
        "performances",
        sa.Column("upload_id", sa.Uuid(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("dislikes", sa.Integer(), nullable=False),
        sa.Column("comments", sa.Integer(), nullable=False),
        sa.Column("shares", sa.Integer(), nullable=False),
        sa.Column("watch_time_seconds", sa.Integer(), nullable=False),
        sa.Column("avg_view_duration", sa.Float(), nullable=False),
        sa.Column("avg_view_percentage", sa.Float(), nullable=False),
        sa.Column("engagement_rate", sa.Float(), nullable=False),
        sa.Column("ctr", sa.Float(), nullable=False),
        sa.Column("subscribers_gained", sa.Integer(), nullable=False),
        sa.Column("subscribers_lost", sa.Integer(), nullable=False),
        sa.Column("traffic_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("demographics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("daily_snapshots", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_high_performer", sa.Boolean(), nullable=False),
        sa.Column("added_to_training", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
            name=op.f("fk_performances_upload_id_uploads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_performances")),
    )
    op.create_index("idx_performance_high", "performances", ["is_high_performer"], unique=False)
    op.create_index("idx_performance_upload", "performances", ["upload_id"], unique=False)
    op.create_index("idx_performance_views", "performances", ["views"], unique=False)
    op.create_index(op.f("ix_performances_id"), "performances", ["id"], unique=False)
    op.create_index(op.f("ix_performances_upload_id"), "performances", ["upload_id"], unique=True)
    # NOTE: Not dropping BM25 index - it was detected due to special index type
    # op.drop_index(op.f('idx_chunks_bm25'), table_name='content_chunks', postgresql_with={'key_field': 'id'}, postgresql_using='bm25')
    op.alter_column(
        "scripts",
        "scenes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Scene-based script structure (list of Scene objects)",
        existing_nullable=True,
    )
    op.add_column("topics", sa.Column("series_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_topics_series_id"), "topics", ["series_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_topics_series_id_series"),
        "topics",
        "series",
        ["series_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_topics_series_id_series"), "topics", type_="foreignkey")
    op.drop_index(op.f("ix_topics_series_id"), table_name="topics")
    op.drop_column("topics", "series_id")
    op.alter_column(
        "scripts",
        "scenes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="Scene-based script structure (list of Scene objects)",
        existing_nullable=True,
    )
    # NOTE: Not recreating BM25 index - it was never dropped
    # op.create_index(op.f('idx_chunks_bm25'), 'content_chunks', ['id', 'terms'], unique=False, postgresql_with={'key_field': 'id'}, postgresql_using='bm25')
    op.drop_index(op.f("ix_performances_upload_id"), table_name="performances")
    op.drop_index(op.f("ix_performances_id"), table_name="performances")
    op.drop_index("idx_performance_views", table_name="performances")
    op.drop_index("idx_performance_upload", table_name="performances")
    op.drop_index("idx_performance_high", table_name="performances")
    op.drop_table("performances")
    op.drop_index(op.f("ix_uploads_youtube_video_id"), table_name="uploads")
    op.drop_index(op.f("ix_uploads_video_id"), table_name="uploads")
    op.drop_index(op.f("ix_uploads_id"), table_name="uploads")
    op.drop_index("idx_upload_youtube_id", table_name="uploads")
    op.drop_index("idx_upload_status", table_name="uploads")
    op.drop_index("idx_upload_scheduled", table_name="uploads")
    op.drop_table("uploads")
    op.drop_index(op.f("ix_series_id"), table_name="series")
    op.drop_index(op.f("ix_series_channel_id"), table_name="series")
    op.drop_index("idx_series_status", table_name="series")
    op.drop_index("idx_series_channel_status", table_name="series")
    op.drop_index("idx_series_channel", table_name="series")
    op.drop_table("series")
    # ### end Alembic commands ###
